# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       gupnp-dlna
Summary:    Utility library for easing DLNA-related tasks
Version:    0.6.6
Release:    0
Group:      Applications/Multimedia
License:    LGPLv2.1
URL:        http://www.gupnp.org
Source0:    http://download.gnome.org/sources/%{name}/0.6/%{name}-%{version}.tar.gz
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(gstreamer-0.10)
BuildRequires:  pkgconfig(gstreamer-plugins-base-0.10)


%description
GUPnP is an object-oriented open source framework for creating UPnP
devices and control points, written in C using GObject and
libsoup. The GUPnP API is intended to be easy to use, efficient and
flexible.

GUPnP DLNA is a small utility library that aims to ease the
DLNA-related tasks such as media profile guessing, transcoding to a
given profile, etc.


%package devel
Summary:    Development files for gupnp-dlna
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Files for development with gupnp-dlna


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
rm -rf  $RPM_BUILD_ROOT%{_datadir}/gtk-doc
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/gupnp-dlna-info
%{_bindir}/gupnp-dlna-ls-profiles
%{_libdir}/libgupnp-dlna-1.0.so.*
%{_datadir}/gupnp-dlna/dlna-profiles/aac.xml
%{_datadir}/gupnp-dlna/dlna-profiles/ac3.xml
%{_datadir}/gupnp-dlna/dlna-profiles/amr.xml
%{_datadir}/gupnp-dlna/dlna-profiles/avc.xml
%{_datadir}/gupnp-dlna/dlna-profiles/common.xml
%{_datadir}/gupnp-dlna/dlna-profiles/dlna-profiles.rng
%{_datadir}/gupnp-dlna/dlna-profiles/jpeg.xml
%{_datadir}/gupnp-dlna/dlna-profiles/lpcm.xml
%{_datadir}/gupnp-dlna/dlna-profiles/mp3.xml
%{_datadir}/gupnp-dlna/dlna-profiles/mpeg-ts.xml
%{_datadir}/gupnp-dlna/dlna-profiles/mpeg1.xml
%{_datadir}/gupnp-dlna/dlna-profiles/mpeg4.xml
%{_datadir}/gupnp-dlna/dlna-profiles/png.xml
%{_datadir}/gupnp-dlna/dlna-profiles/wma.xml
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/gupnp-dlna-1.0/libgupnp-dlna/gupnp-dlna-discoverer.h
%{_includedir}/gupnp-dlna-1.0/libgupnp-dlna/gupnp-dlna-information.h
%{_includedir}/gupnp-dlna-1.0/libgupnp-dlna/gupnp-dlna-profile.h
%{_libdir}/pkgconfig/gupnp-dlna-1.0.pc
%{_libdir}/libgupnp-dlna-1.0.so
# << files devel

